service: severless-ws-test

provider:
  name: aws
  runtime: python3.7
  #runtime: nodejs8.10
  #profile: stepfunctions-user
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ChatTable, Arn]
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource: 
        - "arn:aws:execute-api:*:*:**/@connections/*"

package:
  exclude:
    - exclude-me.js
    - node_modules/**
    - package-lock.json
    - package.json
    - yarn.lock
    - __pycache__/**

functions:
  connectionHandler:
    handler: handler.connectionHandler
    events: 
      - websocket: 
          route: $connect
      - websocket: 
          route: $disconnect
  defaultHandler: 
    handler: handler.defaultHandler
    events: 
      - websocket: 
          route: $default
  sendMessageHandler: 
    handler: handler.sendMessageHandler
    events:
      - websocket:
          route: sendMessage

resources:
  Resources:
    ChatTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "connectionId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "connectionId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: chatIdTable

